### ISSUE TITLE
Installing for single user fails

### ISSUE THREAD

**Issue by minimoe** [getoutofmyyard/igloo#7]
Installing Igloo and selecting "Install for me only" is broken on my machine.

![image](https://user-images.githubusercontent.com/68598/67778277-3df9d400-fa63-11e9-9558-12ac7e82c90c.png)

Trying to run igloo.exe gives the following error message
![image](https://user-images.githubusercontent.com/68598/67777824-95e40b00-fa62-11e9-88b8-09d45d6b009a.png)
```
Traceback (most recent call last):
  File "C:\Users\jared\Desktop\exe-branch\Files\scripts\main.py", line 54, in <module>
  File "C:\Users\jared\Desktop\exe-branch\Files\scripts\main.py", line 43, in parse_file
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\igloo\\command-sets\\cryptoCmds.txt'
[27264] Failed to execute script main
```

Maybe there's some issue with the script building the installer?

**Comment by minimoe** [comment]
I relize this should probably be moved to https://github.com/getoutofmyyard/igloo-exe

**Comment by getoutofmyyard** [comment]
Thanks for pointing that out. It looks like I specified a path during testing and forgot to change it back before pushing.  I'll take a look tonight.

**Comment by getoutofmyyard** [comment]
It does appear to be related to the compiler script. I've re-uploaded the installer with admin-only until I figure out how to fix the single user settings.
